#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmake scalarTransportDBSFoam
wmake dispersionFoam
wmake laplacianFoam
# ----------------------------------------------------------------- end-of-file
